name: iphipi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.5
  audioplayers: ^5.2.1
  dio: ^5.4.3+1

  easy_audio_trimmer: ^1.0.2+4
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.1.0
  flutter_sound: ^9.6.0
  just_audio: ^0.9.38
  path_provider: ^2.1.3
  provider: ^6.1.2
  toastification: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
